import {localize} from 'scripts/localize'

export const actionTexts = localize({
    RU: {
        CRANES_WARN_TITLE: 'Внимание!',
        ADDON_NAME: 'Название',
        ADDON_WHEELS: 'Колёса',
        ADDON_REPAIRS: 'Запчасти',
        ADDON_FUEL: 'Топливо',
        ADDON_CHANGE_BUTTON: 'Изменить',
        ADDON_FILTER: 'Фильтр по имени',
        CHANGED: 'Изменено',
        CRANE: 'кран',
        ADD: 'Добавить',
        REMOVE: 'Удалить',
        CRANES_WARN_MESSAGE: 'Перед удалением крана требуется обязательно его снять с машины.',
        BANDIT_WARN_MESSAGE: 'Для использования требуется купленное DLC с автомобилем KRS 58 "Бандит".',
        SCOUT_TRAILERS: 'Прицепы для скаута',
        TRUCK_TRAILERS: 'Обычные прицепы'
    },
    EN: {
        CRANES_WARN_TITLE: 'Attention!',
        ADDON_NAME: 'Name',
        ADDON_WHEELS: 'Wheels',
        ADDON_REPAIRS: 'Repairs',
        ADDON_FUEL: 'Fuel',
        ADDON_CHANGE_BUTTON: 'Change',
        ADDON_FILTER: 'Filter by name',
        CHANGED: 'Changed',
        CRANE: 'tap',
        ADD: 'Add',
        REMOVE: 'Delete',
        CRANES_WARN_MESSAGE: 'Before removing the tap, be sure to remove it from the machine.',
        BANDIT_WARN_MESSAGE: 'The purchased DLC with the KRS 58 Bandit car is required for use.',
        SCOUT_TRAILERS: 'Scout trailers',
        TRUCK_TRAILERS: 'Conventional trailers'
    },
    DE: {
        CRANES_WARN_TITLE: 'Aufmerksamkeit!',
        ADDON_NAME: 'Name',
        ADDON_WHEELS: 'Ersatzräder',
        ADDON_REPAIRS: 'Ersatzteile',
        ADDON_FUEL: 'Treibstoff',
        ADDON_CHANGE_BUTTON: 'Veränderung',
        ADDON_FILTER: 'Nach Name filtern',
        CHANGED: 'Verändert',
        CRANE: 'klopfen',
        ADD: 'Hinzufügen',
        REMOVE: 'Löschen',
        CRANES_WARN_MESSAGE: 'Bevor Sie den Wasserhahn entfernen, entfernen Sie ihn unbedingt aus der Maschine.',
        BANDIT_WARN_MESSAGE: 'Für die Verwendung ist ein gekaufter DLC mit dem KRS 58 "Bandit" erforderlich.',
        SCOUT_TRAILERS: 'Scout-Anhänger',
        TRUCK_TRAILERS: 'Herkömmliche Anhänger'
    },
    CH: {
        CRANES_WARN_TITLE: '警告!',
        ADDON_NAME: '标题',
        ADDON_WHEELS: '轮子',
        ADDON_REPAIRS: '零件',
        ADDON_FUEL: '燃油',
        ADDON_CHANGE_BUTTON: '变化',
        ADDON_FILTER: '按名称过滤',
        CHANGED: '改变了',
        CRANE: '轻拍',
        ADD: '添加',
        REMOVE: '删除',
        CRANES_WARN_MESSAGE: '在拆除水龙头之前，一定要把它从机器上拆下来。',
        BANDIT_WARN_MESSAGE: '购买的DLC与KRS58"匪"车需要使用。',
        SCOUT_TRAILERS: '侦察员拖车',
        TRUCK_TRAILERS: '传统的拖车'
    }
})
