export async function publishMain() {
	const { publishApp } = await import('@modules/app/main/publisher')
	const { publishArchive } = await import('@modules/archiver/main/publisher')
	const { publishBackup } = await import('@modules/backup/main/publisher')
	const { publishChecks } = await import('@modules/checks/main/publisher')
	const { publishConfig } = await import('@modules/data/config/main/publisher')
	const { publishEdited } = await import('@modules/data/edited/main/publisher')
	const { publishFavorites } = await import('@modules/data/favorites/main/publisher')
	const { publishMods } = await import('@modules/data/modifications/main/publisher')
	const { publishDialogs } = await import('@modules/dialogs/main/publisher')
	const { publishDLCs } = await import('@modules/dlcs/main/publisher')
	const { publishEPF } = await import('@modules/epf/main/publisher')
	const { publishGameTexts } = await import('@modules/game-texts/main/publisher')
	const { publishLoading } = await import('@modules/loading/main/publisher')
	const { publishPaths } = await import('@modules/paths/main/publisher')
	const { publishSystem } = await import('@modules/system/main/publisher')
	const { publishUpdates } = await import('@modules/updates/main/publisher')
	const { publishWindows } = await import('@modules/windows/main/publisher')

	publishApp()
	publishPaths()
	publishSystem()
	publishArchive()
	publishBackup()
	publishConfig()
	publishChecks()
	publishEdited()
	publishFavorites()
	publishMods()
	publishDialogs()
	publishDLCs()
	publishEPF()
	publishGameTexts()
	publishLoading()
	publishUpdates()
	publishWindows()
}
