import { compareWithGlobal } from '#g/texts/renderer'

const $ = compareWithGlobal({
  RU: {
    PHYSICS_WHEELS: 'Дополнительно',
    WHEEL: 'Колесо',
    EXTRA_WHEEL: 'Доп. колесо',
    WHEELS_SIZES: 'Доступные размеры колёс',
    WHEELS_SET: 'Набор колёс',
    WHEELS_SCALE: 'Размер колеса',
    WINCH_LENGTH: 'Длина лебёдки',
    WINCH_STRENGTH: 'Сила лебёдки',
    RESPONSIVENESS: 'Чувствительность руля',
    TORQUE: 'Привод',
    TORQUE_DEFAULT: 'Всегда ведущее',
    TORQUE_FULL: 'Ведущее при полном приводе',
    TORQUE_NONE: 'Ведомое',
    TORQUE_CONNECTABLE: 'Определяется аддоном',
    STEERING_ANGLE: 'Угол поворота',
    CENTER_OF_MASS: 'Смещение центра масс',
    ANY: 'Любая',
    NONE: 'Отсутствует',
    TEXT_GROUP_NAME: 'Тексты',
    UI_DESC: 'Описание',
    UI_NAME: 'Название',
    CONTROL_GROUP_NAME: 'Управление',
    BACK_STEER_SPEED: 'Скорость возврата колёс',
    STEER_SPEED: 'Скорость руля',
    WINCH_GROUP_NAME: 'Лебёдка',
    WHEELS_GROUP_NAME: 'Колёса',
    SUSPENSION_GROUP_NAME: 'Подвеска',
    DIFF_LOCK: 'Блокировка дифференциала',
    INSTALLED: 'Установлена',
    UNINSTALLED: 'Не установлена',
    ALWAYS: 'Всегда',
    GEARBOX_GROUP_NAME: 'Коробка передач',
    ENGINE_GROUP_NAME: 'Двигатель',
    ENGINE_START_DELAY: 'Задержка запуска двигателя',
    EXHAUST_START_TIME: 'Время начала выхлопа',
    FUEL_GROUP_NAME: 'Топливный бак',
    DAMAGE_CAPACITY: 'Прочность',
    FUEL_CAPACITY: 'Объём',
    UNLOCK_GROUP_NAME: 'Разблокировка',
    COUNTRY: 'Страна',
    RUSSIA: 'Россия',
    US: 'США',
    PRICE: 'Цена',
    BY_EXPLORATION: 'Способ разблокировки',
    FIND_ON_MAP: 'Найти на карте',
    BY_RANK: 'По достижению уровня',
    UNLOCK_BY_RANK: 'Уровень разблокировки'
  },
  EN: {
    PHYSICS_WHEELS: 'Extra',
    WHEEL: 'Wheel',
    EXTRA_WHEEL: 'Extra wheel',
    WHEELS_SIZES: 'Available wheel sizes',
    WHEELS_SET: 'Set of wheels',
    WHEELS_SCALE: 'Wheel size',
    WINCH_LENGTH: 'Winch length',
    WINCH_STRENGTH: 'Winch strength',
    RESPONSIVENESS: 'Steering wheel sensitivity',
    TORQUE: 'Type of wheel drive',
    TORQUE_DEFAULT: 'Drive',
    TORQUE_FULL: 'Driving with AWD',
    TORQUE_NONE: 'Driven',
    TORQUE_CONNECTABLE: 'Defined by the addon',
    STEERING_ANGLE: 'Steering angle',
    CENTER_OF_MASS: 'Center of mass offset',
    ANY: 'Any',
    NONE: 'None',
    TEXT_GROUP_NAME: 'Texts',
    UI_DESC: 'Description',
    UI_NAME: 'Name',
    CONTROL_GROUP_NAME: 'Control',
    BACK_STEER_SPEED: 'Back steer speed',
    STEER_SPEED: 'Steer speed',
    WINCH_GROUP_NAME: 'Winch',
    WHEELS_GROUP_NAME: 'Wheels',
    SUSPENSION_GROUP_NAME: 'Suspension',
    DIFF_LOCK: 'Differential lock',
    INSTALLED: 'Installed',
    UNINSTALLED: 'Uninstalled',
    ALWAYS: 'Always',
    GEARBOX_GROUP_NAME: 'Gearbox',
    ENGINE_GROUP_NAME: 'Engine',
    ENGINE_START_DELAY: 'Engine start delay',
    EXHAUST_START_TIME: 'Exhaust start time',
    FUEL_GROUP_NAME: 'Fuel',
    DAMAGE_CAPACITY: 'Damage capacity',
    FUEL_CAPACITY: 'Fuel capacity',
    UNLOCK_GROUP_NAME: 'Unlock',
    COUNTRY: 'Country',
    RUSSIA: 'Russia',
    US: 'USA',
    PRICE: 'Price',
    BY_EXPLORATION: 'Unlock method',
    FIND_ON_MAP: 'Find on map',
    BY_RANK: 'By rank',
    UNLOCK_BY_RANK: 'Unlock level'
  },
  DE: {
    PHYSICS_WHEELS: 'Radantrieb',
    WHEEL: 'Rad',
    EXTRA_WHEEL: 'Zusätzliches Rad',
    WHEELS_SIZES: 'Verfügbare Radgrößen',
    WHEELS_SET: 'Satz von Rädern',
    WHEELS_SCALE: 'Rad-Größe',
    WINCH_LENGTH: 'Länge der Winde',
    WINCH_STRENGTH: 'Kraft der Winde',
    RESPONSIVENESS: 'Empfindlichkeit des Lenkers',
    TORQUE: 'Torsionsart',
    TORQUE_DEFAULT: 'Immer Moderator',
    TORQUE_FULL: 'Allradantrieb',
    TORQUE_NONE: 'Slave',
    TORQUE_CONNECTABLE: 'Definiert durch Addon',
    STEERING_ANGLE: 'Drehwinkel',
    CENTER_OF_MASS: 'Versatz des Massenzentrums',
    ANY: 'Jede',
    NONE: 'Fehlt',
    TEXT_GROUP_NAME: 'Texte',
    UI_NAME: 'Der Name',
    UI_DESC: 'Die Beschreibung',
    CONTROL_GROUP_NAME: 'Kontrolle',
    BACK_STEER_SPEED: 'Die Rücklaufquote der Spitze',
    STEER_SPEED: 'Geschwindigkeit lenken',
    WINCH_GROUP_NAME: 'Winde',
    WHEELS_GROUP_NAME: 'Räder',
    SUSPENSION_GROUP_NAME: 'Aufhängung',
    DIFF_LOCK: 'Differenzialsperre',
    INSTALLED: 'Installiert',
    UNINSTALLED: 'nicht Installiert',
    ALWAYS: 'Immer',
    GEARBOX_GROUP_NAME: 'Getriebe',
    ENGINE_GROUP_NAME: 'Motor',
    ENGINE_START_DELAY: 'Motorstartverzögerung',
    EXHAUST_START_TIME: 'Startzeit des Abgases',
    FUEL_GROUP_NAME: 'Treibstoff',
    DAMAGE_CAPACITY: 'Schadenskapazität',
    FUEL_CAPACITY: 'Kraftstoffkapazität',
    UNLOCK_GROUP_NAME: 'Freischalten',
    COUNTRY: 'Land',
    RUSSIA: 'Russland',
    US: 'Vereinigte Staaten von Amerika',
    PRICE: 'Preis',
    BY_EXPLORATION: 'Methode entsperren',
    FIND_ON_MAP: 'Auf Karte finden',
    BY_RANK: 'Nach Rang',
    UNLOCK_BY_RANK: 'Level freischalten'
  },
  CH: {
    PHYSICS_WHEELS: '单个车轮设置',
    WHEEL: '轮子',
    EXTRA_WHEEL: '额外的轮子',
    WHEELS_SIZES: '可用的车轮尺寸',
    WHEELS_SET: '一套轮子',
    WHEELS_SCALE: '车轮尺寸',
    WINCH_LENGTH: '绞车的长度',
    WINCH_STRENGTH: '绞车的动力',
    RESPONSIVENESS: '舵的敏感性',
    TORQUE: '驱动器',
    TORQUE_DEFAULT: '始终开启全轮驱动',
    TORQUE_FULL: '全轮驱动',
    TORQUE_NONE: '跟随前一组车轮的设定',
    TORQUE_CONNECTABLE: '默认或升级零件决定',
    STEERING_ANGLE: '转弯角度',
    CENTER_OF_MASS: '质量中心的位移',
    ANY: '任何',
    NONE: '没有',
    TEXT_GROUP_NAME: '文本',
    UI_DESC: '简述',
    UI_NAME: '车名',
    CONTROL_GROUP_NAME: '方向盘',
    BACK_STEER_SPEED: '车轮回轮速度',
    STEER_SPEED: '转向速度',
    WINCH_GROUP_NAME: '绞盘',
    WHEELS_GROUP_NAME: '轮子',
    SUSPENSION_GROUP_NAME: '悬架',
    DIFF_LOCK: '差速器锁',
    INSTALLED: '已安装',
    UNINSTALLED: '未安装',
    ALWAYS: '始终开启',
    GEARBOX_GROUP_NAME: '变速箱',
    ENGINE_GROUP_NAME: '发动机',
    ENGINE_START_DELAY: '发动机启动延迟',
    EXHAUST_START_TIME: '排气的开始时间',
    FUEL_GROUP_NAME: '燃油箱',
    DAMAGE_CAPACITY: '耐用性',
    FUEL_CAPACITY: '容量',
    UNLOCK_GROUP_NAME: '解锁',
    COUNTRY: '国家',
    RUSSIA: '俄罗斯',
    US: '美国',
    PRICE: '价格',
    BY_EXPLORATION: '解锁的方法',
    FIND_ON_MAP: '在地图上查找',
    BY_RANK: '当达到该水平时',
    UNLOCK_BY_RANK: '解锁级别'
  }
})

export default $
