import { compareWithGlobal } from '#gl-texts/renderer'

export default compareWithGlobal({
  RU: {
    LOWER_MANUAL_GEAR: 'Точная регулировка',
    AWD_CONSUMPTION_MODIFIER: 'Модификатор потребления топлива при полном приводе',
    CRITICAL_DAMAGE_THRESHOLD: 'Порог критического повреждения',
    DAMAGE_CAPACITY: 'Прочность',
    DAMAGED_CONSUMPTION_MODIFIER: 'Множитель потребления топлива при повреждении',
    FUEL_CONSUMPTION: 'Потребление топлива',
    IDLE_FUEL_CONSUMPTION: 'Множитель потребления топлива в бездействии',
    GEARBOX_PARAMS: 'Наличие передач',
    HIGH_GEAR: 'Повышенная',
    ALLOW: 'Доступно',
    GEAR_ALLOW: 'Доступно',
    GEAR_NOT_ALLOW: 'Недоступно',
    NOT_ALLOW: 'Недоступно',
    LOWER_GEAR: 'Пониженная',
    LOWER_PLUS_GEAR: 'Пониженная+',
    LOWER_MINUS_GEAR: 'Пониженная-',
    REVERSE_GEAR: 'Задняя',
    GEARS: 'Передачи'
  },
  EN: {
    LOWER_MANUAL_GEAR: 'Precise adjustment',
    AWD_CONSUMPTION_MODIFIER: 'AWD consumption modifier',
    CRITICAL_DAMAGE_THRESHOLD: 'Critical damage threshold',
    DAMAGE_CAPACITY: 'Damage capacity',
    DAMAGED_CONSUMPTION_MODIFIER: 'Damage consumption modifier',
    FUEL_CONSUMPTION: 'Fuel consumption',
    IDLE_FUEL_CONSUMPTION: 'IDLE fuel consumption',
    GEARBOX_PARAMS: 'Gears availability',
    HIGH_GEAR: 'High',
    ALLOW: 'Available',
    GEAR_ALLOW: 'Available',
    GEAR_NOT_ALLOW: 'Not Available',
    NOT_ALLOW: 'Not Available',
    LOWER_GEAR: 'Lower',
    LOWER_PLUS_GEAR: 'Lower+',
    LOWER_MINUS_GEAR: 'Lower-',
    REVERSE_GEAR: 'Reverse',
    GEARS: 'Gears'
  },
  DE: {
    LOWER_MANUAL_GEAR: 'Feineinstellung',
    AWD_CONSUMPTION_MODIFIER: 'AWD-Verbrauchsmodifikator',
    CRITICAL_DAMAGE_THRESHOLD: 'Kritische Schadensschwelle',
    DAMAGE_CAPACITY: 'Schadenskapazität',
    DAMAGED_CONSUMPTION_MODIFIER: 'Schadensverbrauchsmodifikator',
    FUEL_CONSUMPTION: 'Kraftstoffverbrauch',
    IDLE_FUEL_CONSUMPTION: 'Leerlaufverbrauch',
    GEARBOX_PARAMS: 'Zahnräder Verfügbarkeit',
    HIGH_GEAR: 'Hoher',
    ALLOW: 'Verfügbar',
    GEAR_ALLOW: 'Verfügbar',
    GEAR_NOT_ALLOW: 'Nicht verfügbar',
    NOT_ALLOW: 'Nicht verfügbar',
    LOWER_GEAR: 'Unterer',
    LOWER_PLUS_GEAR: 'Unterer+',
    LOWER_MINUS_GEAR: 'Unterer-',
    REVERSE_GEAR: 'Rückwärtsgang',
    GEARS: 'Gangs'
  },
  CH: {
    LOWER_MANUAL_GEAR: '微调',
    AWD_CONSUMPTION_MODIFIER: '全轮驱动打开时油耗的倍数',
    CRITICAL_DAMAGE_THRESHOLD: '损伤阈值',
    DAMAGE_CAPACITY: '血量',
    DAMAGED_CONSUMPTION_MODIFIER: '损伤时油耗增加的倍数',
    FUEL_CONSUMPTION: '油耗',
    IDLE_FUEL_CONSUMPTION: '意速时的油耗',
    GEARBOX_PARAMS: '增加的挡位',
    HIGH_GEAR: '高速档',
    ALLOW: '可以',
    GEAR_ALLOW: '可用',
    GEAR_NOT_ALLOW: '不可用',
    NOT_ALLOW: '不可以',
    LOWER_GEAR: '低速',
    LOWER_PLUS_GEAR: '低速+',
    LOWER_MINUS_GEAR: '低速-',
    REVERSE_GEAR: '倒挡',
    GEARS: '标配挡位'
  }
})
