import {localize} from 'scripts/localize'

export const gearboxTexts = localize({
    RU: {
        lowerManualGear: 'Точная регулировка',
        awdConsumptionModifier: 'Модификатор потребления топлива при полном приводе',
        criticalDamageThreshold: 'Порог критического повреждения',
        damageCapacity: 'Прочность',
        damagedConsumptionModifier: 'Множитель потребления топлива при повреждении',
        fuelConsumption: 'Потребление топлива',
        idleFuelConsumption: 'Множитель потребления топлива в бездействии',
        gearboxParams: 'Наличие передач',
        highGear: 'Повышенная',
        allow: 'Доступно',
        gearAllow: 'Доступно',
        gearNotAllow: 'Недоступно',
        notAllow: 'Недоступно',
        lowerGear: 'Пониженная',
        lowerPlusGear: 'Пониженная+',
        lowerMinusGear: 'Пониженная-',
        reverseGear: 'Задняя',
        gears: 'Передачи'
    },
    EN: {
        lowerManualGear: 'Precise adjustment',
        awdConsumptionModifier: 'AWD consumption modifier',
        criticalDamageThreshold: 'Critical damage threshold',
        damageCapacity: 'Damage capacity',
        damagedConsumptionModifier: 'Damage consumption modifier',
        fuelConsumption: 'Fuel consumption',
        idleFuelConsumption: 'IDLE fuel consumption',
        gearboxParams: 'Gears availability',
        highGear: 'High',
        allow: 'Available',
        gearAllow: 'Available',
        gearNotAllow: 'Not Available',
        notAllow: 'Not Available',
        lowerGear: 'Lower',
        lowerPlusGear: 'Lower+',
        lowerMinusGear: 'Lower-',
        reverseGear: 'Reverse',
        gears: 'Gears'
    },
    DE: {
        lowerManualGear: 'Feineinstellung',
        awdConsumptionModifier: 'AWD-Verbrauchsmodifikator',
        criticalDamageThreshold: 'Kritische Schadensschwelle',
        damageCapacity: 'Schadenskapazität',
        damagedConsumptionModifier: 'Schadensverbrauchsmodifikator',
        fuelConsumption: 'Kraftstoffverbrauch',
        idleFuelConsumption: 'Leerlaufverbrauch',
        gearboxParams: 'Zahnräder Verfügbarkeit',
        highGear: 'Hoher',
        allow: 'Verfügbar',
        gearAllow: 'Verfügbar',
        gearNotAllow: 'Nicht verfügbar',
        notAllow: 'Nicht verfügbar',
        lowerGear: 'Unterer',
        lowerPlusGear: 'Unterer+',
        lowerMinusGear: 'Unterer-',
        reverseGear: 'Rückwärtsgang',
        gears: 'Gangs'
    },
    CH: {
        lowerManualGear: '微调',
        awdConsumptionModifier: '全轮驱动打开时油耗的倍数',
        criticalDamageThreshold: '损伤阈值',
        damageCapacity: '血量',
        damagedConsumptionModifier: '损伤时油耗增加的倍数',
        fuelConsumption: '油耗',
        idleFuelConsumption: '意速时的油耗',
        gearboxParams: '增加的挡位',
        highGear: '高速档',
        allow: '可以',
        gearAllow: '可用',
        gearNotAllow: '不可用',
        notAllow: '不可以',
        lowerGear: '低速',
        lowerPlusGear: '低速+',
        lowerMinusGear: '低速-',
        reverseGear: '倒挡',
        gears: '标配挡位'
    }
})
