import localize from "scripts/localize";

export default localize({
    RU: {
        lowerManualGear: "Точная регулировка",
        awdConsumptionModifier: "Модификатор потребления топлива при полном приводе",
        criticalDamageThreshold: "Порог критического повреждения",
        damageCapacity: "Прочность",
        damagedConsumptionModifier: "Множитель потребления топлива при повреждении",
        fuelConsumption: "Потребление топлива",
        idleFuelConsumption: "Множитель потребления топлива в бездействии",
        gearboxParams: "Наличие передач",
        highGear: "Повышенная",
        allow: "Доступно",
        notAllow: "Недоступно",
        lowerGear: "Пониженная",
        lowerPlusGear: "Пониженная+",
        lowerMinusGear: "Пониженная-",
        reverseGear: "Задняя",
        gears: "Передачи"
    },
    EN: {
        lowerManualGear: "Precise adjustment",
        awdConsumptionModifier: "AWD consumption modifier",
        criticalDamageThreshold: "Critical damage threshold",
        damageCapacity: "Damage capacity",
        damagedConsumptionModifier: "Damage consumption modifier",
        fuelConsumption: "Fuel consumption",
        idleFuelConsumption: "IDLE fuel consumption",
        gearboxParams: "Gears availability",
        highGear: "High",
        allow: "Available",
        notAllow: "Not Available",
        lowerGear: "Lower",
        lowerPlusGear: "Lower+",
        lowerMinusGear: "Lower-",
        reverseGear: "Reverce",
        gears: "Gears"
    },
    DE: {
        lowerManualGear: "Feineinstellung",
        awdConsumptionModifier: "AWD-Verbrauchsmodifikator",
        criticalDamageThreshold: "Kritische Schadensschwelle",
        damageCapacity: "Schadenskapazität",
        damagedConsumptionModifier: "Schadensverbrauchsmodifikator",
        fuelConsumption: "Kraftstoffverbrauch",
        idleFuelConsumption: "Leerlaufverbrauch",
        gearboxParams: "Zahnräder Verfügbarkeit",
        highGear: "Hoher",
        allow: "Verfügbar",
        notAllow: "Nicht verfügbar",
        lowerGear: "Unterer",
        lowerPlusGear: "Unterer+",
        lowerMinusGear: "Unterer-",
        reverseGear: "Rückwärtsgang",
        gears: "Gangs"
    },
    CH: {
        lowerManualGear: "微调",
        awdConsumptionModifier: "全轮驱动的油耗修改器",
        criticalDamageThreshold: "危急伤害阈值",
        damageCapacity: "耐用性",
        damagedConsumptionModifier: "损害的燃料消耗乘数",
        fuelConsumption: "燃料消耗",
        idleFuelConsumption: "怠速时的油耗倍率",
        gearboxParams: "齿轮的可用性",
        highGear: "增加",
        allow: "可从",
        notAllow: "不详",
        lowerGear: "减少了",
        lowerPlusGear: "减少+",
        lowerMinusGear: "减少-",
        reverseGear: "后部",
        gears: "传动装置"
    }
});
