import Config from 'main/classes/Config'

export const texts = {
	RU: {
		physicsWheels: 'Дополнительно',
		wheel: 'Колесо',
		extraWheel: 'Доп. колесо',
		wheelsSizes: 'Доступные размеры колёс',
		wheelsSet: 'Набор колёс',
		wheelScale: 'Размер колеса',
		winchLength: 'Длина лебёдки',
		winchStrength: 'Сила лебёдки',
		responsiveness: 'Чувствительность руля',
		torque: 'Привод',
		torqueDefault: 'Всегда ведущее',
		torqueFull: 'Ведущее при полном приводе',
		torqueNone: 'Ведомое',
		torqueConnectable: 'Определяется аддоном',
		steeringAngle: 'Угол поворота',
		centerOfMass: 'Смещение центра масс',
		any: 'Любая',
		none: 'Отсутствует',
		textGroupName: 'Тексты',
		UIDesc: 'Описание',
		UIName: 'Название',
		controlGroupName: 'Управление',
		backSteerSpeed: 'Скорость возврата колёс',
		steerSpeed: 'Скорость руля',
		winchGroupName: 'Лебёдка',
		wheelsGroupName: 'Колёса',
		suspensionGroupName: 'Подвеска',
		diffLock: 'Блокировка дифференциала',
		installed: 'Установлена',
		uninstalled: 'Не установлена',
		always: 'Всегда',
		gearboxGroupName: 'Коробка передач',
		engineGroupName: 'Двигатель',
		engineStartDelay: 'Задержка запуска двигателя',
		exhaustStartTime: 'Время начала выхлопа',
		fuelGroupName: 'Топливный бак',
		damageCapacity: 'Прочность',
		fuelCapacity: 'Объём',
		unlockGroupName: 'Разблокировка',
		country: 'Страна',
		russia: 'Россия',
		us: 'США',
		price: 'Цена',
		byExploration: 'Способ разблокировки',
		findOnMap: 'Найти на карте',
		byRank: 'По достижению уровня',
		unlockByRank: 'Уровень разблокировки'
	},
	EN: {
		physicsWheels: 'Extra',
		wheel: 'Wheel',
		extraWheel: 'Extra wheel',
		wheelsSizes: 'Available wheel sizes',
		wheelsSet: 'Set of wheels',
		wheelScale: 'Wheel size',
		winchLength: 'Winch length',
		winchStrength: 'Winch strength',
		responsiveness: 'Steering wheel sensitivity',
		torque: 'Drive',
		torqueDefault: 'Always leading',
		torqueFull: 'Driving with all-wheel drive',
		torqueNone: 'Slave',
		torqueConnectable: 'Defined by the addon',
		steeringAngle: 'Steering angle',
		centerOfMass: 'Center of mass offset',
		any: 'Any',
		none: 'None',
		textGroupName: 'Texts',
		UIDesc: 'Description',
		UIName: 'Name',
		controlGroupName: 'Control',
		backSteerSpeed: 'Back steer speed',
		steerSpeed: 'Steer speed',
		winchGroupName: 'Winch',
		wheelsGroupName: 'Wheels',
		suspensionGroupName: 'Suspension',
		diffLock: 'Differential lock',
		installed: 'Installed',
		uninstalled: 'Uninstalled',
		always: 'Always',
		gearboxGroupName: 'Gearbox',
		engineGroupName: 'Engine',
		engineStartDelay: 'Engine start delay',
		exhaustStartTime: 'Exhaust start time',
		fuelGroupName: 'Fuel',
		damageCapacity: 'Damage capacity',
		fuelCapacity: 'Fuel capacity',
		unlockGroupName: 'Unlock',
		country: 'Country',
		russia: 'Russia',
		us: 'USA',
		price: 'Price',
		byExploration: 'Unlock method',
		findOnMap: 'Find on map',
		byRank: 'By rank',
		unlockByRank: 'Unlock level'
	},
	DE: {
		physicsWheels: 'Radantrieb',
		wheel: 'Rad',
		extraWheel: 'Zusätzliches Rad',
		wheelsSizes: 'Verfügbare Radgrößen',
		wheelsSet: 'Satz von Rädern',
		wheelScale: 'Rad-Größe',
		winchLength: 'Länge der Winde',
		winchStrength: 'Kraft der Winde',
		responsiveness: 'Empfindlichkeit des Lenkers',
		torque: 'Torsionsart',
		torqueDefault: 'Immer Moderator',
		torqueFull: 'Allradantrieb',
		torqueNone: 'Slave',
		torqueConnectable: 'Definiert durch Addon',
		steeringAngle: 'Drehwinkel',
		centerOfMass: 'Versatz des Massenzentrums',
		any: 'Jede',
		none: 'Fehlt',
		textGroupName: 'Texte',
		UIName: 'Der Name',
		UIDesc: 'Die Beschreibung',
		controlGroupName: 'Kontrolle',
		backSteerSpeed: 'Die Rücklaufquote der Spitze',
		steerSpeed: 'Geschwindigkeit lenken',
		winchGroupName: 'Winde',
		wheelsGroupName: 'Räder',
		suspensionGroupName: 'Aufhängung',
		diffLock: 'Differenzialsperre',
		installed: 'Installiert',
		uninstalled: 'nicht Installiert',
		always: 'Immer',
		gearboxGroupName: 'Getriebe',
		engineGroupName: 'Motor',
		engineStartDelay: 'Motorstartverzögerung',
		exhaustStartTime: 'Startzeit des Abgases',
		fuelGroupName: 'Treibstoff',
		damageCapacity: 'Schadenskapazität',
		fuelCapacity: 'Kraftstoffkapazität',
		unlockGroupName: 'Freischalten',
		country: 'Land',
		russia: 'Russland',
		us: 'Vereinigte Staaten von Amerika',
		price: 'Preis',
		byExploration: 'Methode entsperren',
		findOnMap: 'Auf Karte finden',
		byRank: 'Nach Rang',
		unlockByRank: 'Level freischalten'
	},
	CH: {
		physicsWheels: '锦上添花',
		wheel: '轮子',
		extraWheel: '额外的轮子',
		wheelsSizes: '可用的车轮尺寸',
		wheelsSet: '一套轮子',
		wheelScale: '车轮尺寸',
		winchLength: '绞车的长度',
		winchStrength: '绞车的动力',
		responsiveness: '舵的敏感性',
		torque: '驱动器',
		torqueDefault: '始终引领潮流',
		torqueFull: '领先的全轮驱动',
		torqueNone: '奴隶',
		torqueConnectable: '由附加组件定义的',
		steeringAngle: '转弯角度',
		centerOfMass: '质量中心的位移',
		any: '任何',
		none: '不详',
		textGroupName: '文本',
		UIDesc: '描述',
		UIName: '标题',
		controlGroupName: '管理',
		backSteerSpeed: '车轮回轮速度',
		steerSpeed: '转向速度',
		winchGroupName: '绞盘',
		wheelsGroupName: '轮子',
		suspensionGroupName: '悬挂',
		diffLock: '差速器锁',
		installed: '已安装',
		uninstalled: '未建立',
		always: '始终如一',
		gearboxGroupName: '变速箱',
		engineGroupName: '发动机',
		engineStartDelay: '发动机启动延迟',
		exhaustStartTime: '排气的开始时间',
		fuelGroupName: '燃油箱',
		damageCapacity: '耐用性',
		fuelCapacity: '卷宗',
		unlockGroupName: '解锁',
		country: '国家',
		russia: '俄罗斯',
		us: '美国',
		price: '价格',
		byExploration: '解锁的方法',
		findOnMap: '在地图上查找',
		byRank: '当达到该水平时',
		unlockByRank: '解锁级别'
	}
}[Config.obj.lang]

export const descs = {
	RU: {
		UIName: 'Название авто в игре (либо ключ перевода)',
		UIDesc: 'Описание авто в игре (либо ключ перевода)',
		backSteerSpeed: 'Скорость, с которой колёса возвращаются на исходную позицию после поворота',
		steerSpeed: 'Скорость, с которой поворачивается руль.',
		isUpgradable: 'Улучшается ли лебёдка',
		diffLock: 'Настройки блокировки дифференциала',
		exhaustStartTime: 'Время начала визуализации выхлопа.',
		engineStartDelay: 'Задержка после нажатия "включить двигатель"',
		damageCapacity: 'Запас прочности бензобака',
		fuelCapacity: 'Максимальное количество топлива в баке',
		country: 'Страна разблокировки',
		price: 'Цена самого автомобиля (без учёта составляющих)',
		byExploration: 'Способ разблокировки автомобиля',
		unlockByRank: 'Уровень разблокировки автомобиля',
		centerOfMass: 'Смещение центра масс тела относительно центра масс, рассчитанного движком игры',
		torque: 'То, когда колесо будет ведущим',
		steeringAngle: 'Максимальный угол поворота колеса при рулении'
	},
	EN: {
		UIName: 'The name of the car in the game (or the transfer key)',
		UIDesc: 'Description of the car in the game (or the transfer key)',
		backSteerSpeed: 'The speed at which the wheels return to their original position after turning',
		steerSpeed: 'The speed at which the steering wheel turns.',
		isUpgradable: 'Is the winch improving',
		diffLock: 'Differential Lock Settings',
		exhaustStartTime: 'The start time of the exhaust visualization.',
		engineStartDelay: 'Delay after pressing "turn on the engine"',
		damageCapacity: 'Fuel tank safety margin',
		fuelCapacity: 'Maximum amount of fuel in the tank',
		country: 'Unlock country',
		price: 'Der Preis des Autos selbst (ohne die Komponenten)',
		byExploration: 'How to unlock the car',
		unlockByRank: 'Car Unlock Level',
		centerOfMass: 'The displacement of the center of mass of the body relative to the center of mass calculated by the game engine',
		torque: 'When the wheel will be leading',
		steeringAngle: 'Maximum steering angle of the wheel'
	},
	DE: {
		UIName: 'Name des Autos im Spiel (oder Übersetzungsschlüssel)',
		UIDesc: 'Beschreibung von Auto im Spiel (oder Schlüssel Übersetzung)',
		backSteerSpeed: 'Die Geschwindigkeit, mit der die Räder nach dem Abbiegen in die Ausgangsposition zurückkehren',
		steerSpeed: 'Die Geschwindigkeit, mit der sich das Lenkrad dreht.',
		isUpgradable: 'Verbessert sich die Winde',
		diffLock: 'Differentialsperre Einstellungen',
		exhaustStartTime: 'Startzeit Visualisierung Auspuff.',
		engineStartDelay: 'Verzögerung nach dem Drücken von "Motor einschalten"',
		damageCapacity: 'Sicherheitsmarge des Benzinbehälters',
		fuelCapacity: 'Maximale Kraftstoffmenge im Tank',
		country: 'Land entsperren',
		price: 'The price of the car itself (excluding components)',
		byExploration: 'Methode zum Entsperren des Autos',
		unlockByRank: 'Auto entsperren Ebene',
		centerOfMass: 'Verschiebung der Körpermassenmitte relativ zum von der Spiel-Engine berechneten Massenzentrum',
		torque: 'Wann das Rad fahren wird',
		steeringAngle: 'Maximaler Lenkwinkel des Rades beim Lenken'
	},
	CH: {
		UIName: '游戏中的汽车名称（或翻译键）。',
		UIDesc: '游戏中的汽车描述（或翻译键）。',
		backSteerSpeed: '车轮转弯后返回原位的速度',
		steerSpeed: '转动方向盘的速度。',
		isUpgradable: '绞车是否在改进',
		diffLock: '差速器锁设置',
		exhaustStartTime: '视觉化排气的开始时间。',
		engineStartDelay: '按下 "打开发动机" 后的延迟',
		damageCapacity: '汽油箱的安全系数',
		fuelCapacity: '油箱中的最大燃料量',
		country: '疏通国家',
		price: '汽车本身的价格（不包括零部件）。',
		byExploration: '解锁车辆的方法',
		unlockByRank: '车辆解锁级别',
		centerOfMass: '游戏引擎计算的身体质心相对于质心的位移。',
		torque: '哦，当车轮将被引导',
		steeringAngle: '最大的车轮转向角'
	}
}[Config.obj.lang]
