import {localize} from 'scripts/localize'

export const truckTexts = localize({
    RU: {
        physicsWheels: 'Дополнительно',
        wheel: 'Колесо',
        extraWheel: 'Доп. колесо',
        wheelsSizes: 'Доступные размеры колёс',
        wheelsSet: 'Набор колёс',
        wheelScale: 'Размер колеса',
        winchLength: 'Длина лебёдки',
        winchStrength: 'Сила лебёдки',
        responsiveness: 'Чувствительность руля',
        torque: 'Привод',
        torqueDefault: 'Всегда ведущее',
        torqueFull: 'Ведущее при полном приводе',
        torqueNone: 'Ведомое',
        torqueConnectable: 'Определяется аддоном',
        steeringAngle: 'Угол поворота',
        centerOfMass: 'Смещение центра масс',
        any: 'Любая',
        none: 'Отсутствует',
        textGroupName: 'Тексты',
        UIDesc: 'Описание',
        UIName: 'Название',
        controlGroupName: 'Управление',
        backSteerSpeed: 'Скорость возврата колёс',
        steerSpeed: 'Скорость руля',
        winchGroupName: 'Лебёдка',
        wheelsGroupName: 'Колёса',
        suspensionGroupName: 'Подвеска',
        diffLock: 'Блокировка дифференциала',
        installed: 'Установлена',
        uninstalled: 'Не установлена',
        always: 'Всегда',
        gearboxGroupName: 'Коробка передач',
        engineGroupName: 'Двигатель',
        engineStartDelay: 'Задержка запуска двигателя',
        exhaustStartTime: 'Время начала выхлопа',
        fuelGroupName: 'Топливный бак',
        damageCapacity: 'Прочность',
        fuelCapacity: 'Объём',
        unlockGroupName: 'Разблокировка',
        country: 'Страна',
        russia: 'Россия',
        us: 'США',
        price: 'Цена',
        byExploration: 'Способ разблокировки',
        findOnMap: 'Найти на карте',
        byRank: 'По достижению уровня',
        unlockByRank: 'Уровень разблокировки'
    },
    EN: {
        physicsWheels: 'Extra',
        wheel: 'Wheel',
        extraWheel: 'Extra wheel',
        wheelsSizes: 'Available wheel sizes',
        wheelsSet: 'Set of wheels',
        wheelScale: 'Wheel size',
        winchLength: 'Winch length',
        winchStrength: 'Winch strength',
        responsiveness: 'Steering wheel sensitivity',
        torque: 'Type of wheel drive',
        torqueDefault: 'Drive',
        torqueFull: 'Driving with AWD',
        torqueNone: 'Driven',
        torqueConnectable: 'Defined by the addon',
        steeringAngle: 'Steering angle',
        centerOfMass: 'Center of mass offset',
        any: 'Any',
        none: 'None',
        textGroupName: 'Texts',
        UIDesc: 'Description',
        UIName: 'Name',
        controlGroupName: 'Control',
        backSteerSpeed: 'Back steer speed',
        steerSpeed: 'Steer speed',
        winchGroupName: 'Winch',
        wheelsGroupName: 'Wheels',
        suspensionGroupName: 'Suspension',
        diffLock: 'Differential lock',
        installed: 'Installed',
        uninstalled: 'Uninstalled',
        always: 'Always',
        gearboxGroupName: 'Gearbox',
        engineGroupName: 'Engine',
        engineStartDelay: 'Engine start delay',
        exhaustStartTime: 'Exhaust start time',
        fuelGroupName: 'Fuel',
        damageCapacity: 'Damage capacity',
        fuelCapacity: 'Fuel capacity',
        unlockGroupName: 'Unlock',
        country: 'Country',
        russia: 'Russia',
        us: 'USA',
        price: 'Price',
        byExploration: 'Unlock method',
        findOnMap: 'Find on map',
        byRank: 'By rank',
        unlockByRank: 'Unlock level'
    },
    DE: {
        physicsWheels: 'Radantrieb',
        wheel: 'Rad',
        extraWheel: 'Zusätzliches Rad',
        wheelsSizes: 'Verfügbare Radgrößen',
        wheelsSet: 'Satz von Rädern',
        wheelScale: 'Rad-Größe',
        winchLength: 'Länge der Winde',
        winchStrength: 'Kraft der Winde',
        responsiveness: 'Empfindlichkeit des Lenkers',
        torque: 'Torsionsart',
        torqueDefault: 'Immer Moderator',
        torqueFull: 'Allradantrieb',
        torqueNone: 'Slave',
        torqueConnectable: 'Definiert durch Addon',
        steeringAngle: 'Drehwinkel',
        centerOfMass: 'Versatz des Massenzentrums',
        any: 'Jede',
        none: 'Fehlt',
        textGroupName: 'Texte',
        UIName: 'Der Name',
        UIDesc: 'Die Beschreibung',
        controlGroupName: 'Kontrolle',
        backSteerSpeed: 'Die Rücklaufquote der Spitze',
        steerSpeed: 'Geschwindigkeit lenken',
        winchGroupName: 'Winde',
        wheelsGroupName: 'Räder',
        suspensionGroupName: 'Aufhängung',
        diffLock: 'Differenzialsperre',
        installed: 'Installiert',
        uninstalled: 'nicht Installiert',
        always: 'Immer',
        gearboxGroupName: 'Getriebe',
        engineGroupName: 'Motor',
        engineStartDelay: 'Motorstartverzögerung',
        exhaustStartTime: 'Startzeit des Abgases',
        fuelGroupName: 'Treibstoff',
        damageCapacity: 'Schadenskapazität',
        fuelCapacity: 'Kraftstoffkapazität',
        unlockGroupName: 'Freischalten',
        country: 'Land',
        russia: 'Russland',
        us: 'Vereinigte Staaten von Amerika',
        price: 'Preis',
        byExploration: 'Methode entsperren',
        findOnMap: 'Auf Karte finden',
        byRank: 'Nach Rang',
        unlockByRank: 'Level freischalten'
    },
    CH: {
        physicsWheels: '单个车轮设置',
        wheel: '轮子',
        extraWheel: '额外的轮子',
        wheelsSizes: '可用的车轮尺寸',
        wheelsSet: '一套轮子',
        wheelScale: '车轮尺寸',
        winchLength: '绞车的长度',
        winchStrength: '绞车的动力',
        responsiveness: '舵的敏感性',
        torque: '驱动器',
        torqueDefault: '始终开启全轮驱动',
        torqueFull: '全抡驱动',
        torqueNone: '跟随前一组车轮的设定',
        torqueConnectable: '默认或升级零件决定',
        steeringAngle: '转弯角度',
        centerOfMass: '质量中心的位移',
        any: '任何',
        none: '不详',
        textGroupName: '文本',
        UIDesc: '简述',
        UIName: '车名',
        controlGroupName: '方向盘',
        backSteerSpeed: '车轮回轮速度',
        steerSpeed: '转向速度',
        winchGroupName: '绞盘',
        wheelsGroupName: '轮子',
        suspensionGroupName: '悬架',
        diffLock: '差速器锁',
        installed: '已安装',
        uninstalled: '未建立',
        always: '始终如一',
        gearboxGroupName: '变速箱',
        engineGroupName: '发动机',
        engineStartDelay: '发动机启动延迟',
        exhaustStartTime: '排气的开始时间',
        fuelGroupName: '燃油箱',
        damageCapacity: '耐用性',
        fuelCapacity: '容量',
        unlockGroupName: '解锁',
        country: '国家',
        russia: '俄罗斯',
        us: '美国',
        price: '价格',
        byExploration: '解锁的方法',
        findOnMap: '在地图上查找',
        byRank: '当达到该水平时',
        unlockByRank: '解锁级别'
    }
})
