import {localize} from 'scripts/localize'

export const listsTexts = localize({
    RU: {
        MODS_CHANGE_BUTTON: 'Изменить',
        RELAUNCH_PROMPT: 'Для загрузки мода необходима перезагрузка программы. Выполнить перезагрузку?',
        ADD_FAVORITE: 'Добавить в избранное',
        REMOVE_FAVORITE: 'Удалить из избранного',
        MANUAL_MOD: 'Выбрать вручную',
        MODS_POPUP_TITLE: 'Модификации',
        SEARCH: 'Поиск',
        DLC_LIST_TITLE: 'Из DLC',
        FAVORITES_LIST_TITLE: 'Избранное',
        MAIN_LIST_TITLE: 'Базовые',
        MODS_LIST_TITLE: 'Из модов',
        TRUCKS_LIST_TITLE: 'Список авто',
        TRAILERS_LIST_TITLE: 'Список прицепов',
        TRAILERS_CATEGORY_TITLE: 'Прицепы',
        TRUCKS_CATEGORY_TITLE: 'Автомобили'
    },
    EN: {
        MODS_CHANGE_BUTTON: 'Change',
        RELAUNCH_PROMPT: 'To add the mod, you need to restart the program. Perform a reboot?',
        ADD_FAVORITE: 'Add to Favorites',
        REMOVE_FAVORITE: 'Delete from Favorites',
        MANUAL_MOD: 'Select manually',
        MODS_POPUP_TITLE: 'Modifications',
        SEARCH: 'Search',
        DLC_LIST_TITLE: 'From DLC',
        FAVORITES_LIST_TITLE: 'Favorites',
        MAIN_LIST_TITLE: 'Basic',
        MODS_LIST_TITLE: 'From mods',
        TRUCKS_LIST_TITLE: 'Auto list',
        TRAILERS_LIST_TITLE: 'List of trailers',
        TRAILERS_CATEGORY_TITLE: 'Trailers',
        TRUCKS_CATEGORY_TITLE: 'Trucks'
    },
    DE: {
        MODS_CHANGE_BUTTON: 'Ändern',
        RELAUNCH_PROMPT: 'Um den Mod zu laden, müssen Sie das Programm neu starten. Einen Neustart durchführen?',
        ADD_FAVORITE: 'Zu Favoriten hinzufügen',
        REMOVE_FAVORITE: 'Aus Favoriten entfernen',
        MANUAL_MOD: 'Manuell auswählen',
        MODS_POPUP_TITLE: 'Änderungen',
        SEARCH: 'Suche',
        DLC_LIST_TITLE: 'Von DLC',
        FAVORITES_LIST_TITLE: 'Auswahl',
        MAIN_LIST_TITLE: 'Basic',
        MODS_LIST_TITLE: 'Von Mods',
        TRUCKS_LIST_TITLE: 'Automatische Liste',
        TRAILERS_LIST_TITLE: 'Liste der Anhänger',
        TRAILERS_CATEGORY_TITLE: 'Nutzfahrzeuge',
        TRUCKS_CATEGORY_TITLE: 'Autos'
    },
    CH: {
        MODS_CHANGE_BUTTON: '变化',
        RELAUNCH_PROMPT: '要下载mod, 你需要重新启动软件。进行重新启动?',
        ADD_FAVORITE: '添加到收藏夹',
        REMOVE_FAVORITE: '从收藏夹中删除',
        MANUAL_MOD: '手动选择',
        MODS_POPUP_TITLE: '修改',
        SEARCH: '搜索',
        DLC_LIST_TITLE: '来自于DLC',
        FAVORITES_LIST_TITLE: '收藏',
        MAIN_LIST_TITLE: '基本',
        MODS_LIST_TITLE: '来自修改者',
        TRUCKS_LIST_TITLE: '汽车清单',
        TRAILERS_LIST_TITLE: '拖车清单',
        TRAILERS_CATEGORY_TITLE: '拖车',
        TRUCKS_CATEGORY_TITLE: '汽车'
    }
})
